### PR TITLE
RT #52317 document limitation where STDIN may be clobbered

### PR DESCRIPTION
**Pull request by plicease**
This attempts to resolve rt#52317 here https://rt.cpan.org/Public/Bug/Display.html?id=52317, which has been (as of this late writing) been marked as resolved.

RSCHUPP commented there:

> My patch doesn't work. On some platforms (e.g. OSX) it fails immediately, on others it fails if you try harder.
> 
> STDIN can't be reliably saved and restored by any means.

### CODE REVIEW

**Comment by gregoa** [comment]
Any progress here? Obviously a fix would be nicer but at least documenting the issue might avoid users some hassles, e.g. https://bugs.debian.org/1060798

**Comment by rjbs** [comment]
Obviously this repo isn't getting heavy rotation on updates.

Can you give us more details on which platforms are affected?

**Comment by rjbs** [comment]
(this would need re-opening after switching default branch to "main", sorry)

**Comment by plicease** [comment]
@rjbs I've updated the issue description with a reference to the comment that led me to open this PR.  (sorry for leaving it blank!)

**Comment by gregoa** [comment]
The referenced Debian bug occured on a linux system (with x86_64 architecture).

**Pull request closed without merging**
